# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Boy's Shorts
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Short posts and daily updates.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:year/:month/:day/:title
url: "https://shorts.boy.sh" # the base hostname & protocol for your site, e.g. http://example.com
author: Boy 🛸
avatar: /assets/img/avatar.jpg
twitter_username: boyvanamstel
github_username: boyvanamstel
microblog_username: boyvanamstel
google_analytics: #UA-7720147-37

paginate: 5
paginate_path: "/page/:num"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-assets
  - octopress-minify-html
  - jekyll-sitemap
  - jekyll-paginate
include:
  - _redirects

# jekyll-assets
assets:
  prefix: "/assets"
  digest: true
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
  features:
    automatic_img_size: false

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/avatar.jpg
