---
label: Default
hide_body: false
is_partial: false
fields:
- type: select
  name: layout
  config:
    source:
      type: simple
    options:
    - post
    required: true
  label: Layout
  default: post
- type: text
  name: title
  label: Title
  config:
    required: false
pages:
- _posts/2019-02-17-google-analytics.md
- _posts/2019-02-11-uiimagecolors-macos.md
- _posts/2019-01-29-resident-evil-2-remake.md
- _posts/2019-01-23-forestry.md
- _posts/2019-01-24-issuehunt.md
