---
label: Default
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: false
- type: datetime
  name: date
  label: Date
  config:
    required: true
