---
label: Default
hide_body: false
fields:
- type: select
  name: layout
  config:
    source:
      type: simple
    options:
    - post
    required: true
  label: Layout
  default: post
  hidden: true
- type: text
  name: title
  label: Title
  config:
    required: false
  showOnly:
    field: microblog
- name: microblog
  type: boolean
  label: Microblog
  default: true
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
  default: now
pages:
- _posts/2019-01-23-forestry.md
- _posts/2019-01-24-issuehunt.md
- _posts/2019-01-29-resident-evil-2-remake.md
- _posts/2019-02-11-uiimagecolors-macos.md
- _posts/2019-02-17-google-analytics.md
- _posts/2019-04-07-launching-repair-alert.md
- _posts/2019-05-30-posts-boy-sh.md
